name = "CodecBGZF"
uuid = "d9d91ef6-315d-495b-8131-db2ca24339d6"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
version = "0.1.1"

[deps]
LibDeflate = "9255714d-24a7-4b30-8ea3-d46a97f7e13b"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
TranscodingStreams = "0.9"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
